<a href="https://colab.research.google.com/github/craiggossen/Projects/blob/main/NumPy_Bakery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Bakery Assignment


- Student Name: Craig Gossen


## Instructions

 The first portion of the notebook is the content from the related lesson that is required to continue the activity. 
 
- Jump down to the "✍️ **Assignment Starts Here**" header to begin your work.


#  📚 Bake Sale Mini-Project (From Lesson)

## Our Task


Often in your work as a data science you will be loading outside datasets into your Python environment.  Today, however, we will create a simple data set for a mini-project analyzing the results of a bake sale.

Let's suppose the "Teens for Tech" club has asked you to help them analyze data from their ongoing bake sale.  

- They are planning on selling the following baked goods every day for a week.
    - brownie: \$2
    - cookie: \$1
    - cake: $10

- They were hoping to raise $200. 





## 1) Starting with Lists

#### Names
1. Declare a variable, `names_list`, that is a list containing the names of the baked goods they plan to sell.
2. Print the names list.


In [1]:
names_list = ['brownie','cookie','cake']
print(names_list)

['brownie', 'cookie', 'cake']


#### Prices



1. Declare a second variable, `prices_list`, that is a list containing the prices of each good (as integers). 
    - Make that you have the names and prices in the same order (if brownie is first in your names list, then its price should be the first value in your prices list).


2. Print the prices list.


In [2]:
prices_list = [2,1,10]
print(prices_list)

[2, 1, 10]


## Bake Sale Results (So Far)

#### Quantities Sold

- So far, the club has sold:
    - 17 brownies
    - 40 cookies
    - and 1 cake.  

1. Declare a new list with these values called `quantities_sold_list`.
2. Print the quantities_sold_list.



In [3]:
quantities_sold_list = [17, 40, 1]
print(quantities_sold_list)

[17, 40, 1]


### Calculating the Sales

You should now have:
- a list called `names` that contains 'brownie', 'cookie', 'cake'
-  a list called `prices` that contains 2,1,10.
- a list called `quantity_sold` that contains 17, 40, 1.


We want to calculate the total money earned from each of the baked goods so far. We simply need to multiple each price by the corresponding quanity sold. 


In [4]:
# prices_list * quantities_sold_list

##  Creating a NumPy Array


In [5]:
import numpy as np

### Converting Our Lists to 1-dimensional Arrays



You can use the function `np.array()` to change a Python collection into a NumPy array.

- Create new numpy array versions of the `prices_list`, `quantities_sold_list`, and `names_list`.
    - We can drop the `_list` from the names of our new variables.
- Print each of them

The result should look like a list with no commas.

In [6]:
names = np.array(names_list)
print(names)


prices = np.array(prices_list)
print(prices)

quantities_sold = np.array(quantities_sold_list)
print(quantities_sold)

['brownie' 'cookie' 'cake']
[ 2  1 10]
[17 40  1]




Arrays are ordered and mutable, just like lists, but they are faster to and more efficient to store in memory.


### Arrays can be multiplied



#### Calculating Our Sales (For real this time!)

In [7]:
prices * quantities_sold

array([34, 40, 10])

## 4) Elementwise Calculations



As you saw anobe we calcualted the revenue for each bake good so far, the multiplication was applied between the first element of each array, then between the second element of each array, and so on.   This is known as an ***"elementwise" calculation***.  



Let's look at another example of elementwise calculations by factoring in the cost to make each baked good.




#### Accounting for Costs

The club wants to account for the cost of each baked good so that we can calculate the revenue for each baked good (Revenue = profit - cost).

The cost to make each baked good is:
- a brownie costs \$0.25 to make.
- a cookie costs \$0.50 to make.
- a cake costs \$5.00 to make.



Now, let's create an array that corresponds to the cost to make each of the items sold at the bake sale.


In [8]:
cost_list = [0.25, 0.50, 5.00]
costs = np.array(cost_list)
print(costs)

[0.25 0.5  5.  ]


- Note: we can actually do this in 1 step by creating our list inside of np.array instead of saving it as a separate varaible first.

In [9]:
expenses = np.array([0.25, 0.50, 5.00])
print(expenses)

[0.25 0.5  5.  ]


### Calculating Profits 

- To find the profit of each baked good, we want to subtract the cost from the price. 


In [10]:
profits = prices - expenses
profits

array([1.75, 0.5 , 5.  ])

## 5) Appending, Deleting, and Replacing Elements in a NumPy 

#### Appending



The club will also sell pies for $7 so we need to update our price_array.  

Based on your experience with lists, ***you might think the following code would work*** to include an additional element to our array:  

In [11]:
prices = prices + [7]
prices

array([ 9,  8, 17])

Wait! This is **not** the output we wanted!   The NumPy array did what it does best: it added seven to *each element* in the array.  

To get back to the original values, we will subtract 7, then use the np.append() function to include the value 7 as desired.

In [12]:
# Just fixing the mistake
prices = prices - [7]
prices

array([ 2,  1, 10])

In [13]:
# The proper way to append an element to an array
prices = np.append(prices, 7)
prices

array([ 2,  1, 10,  7])

- Let's also append the name for our new baked good to our names array.

In [14]:
names = np.append(names, 'pie')
names

array(['brownie', 'cookie', 'cake', 'pie'], dtype='<U7')

##### Appending Multiple Elements at Once

You can also append multiple values to the array in one command.  

For example, the club want to add the following prices:  
  - \$4.50 for fudge
  - \$3 for a cupcake
  - \$4 for a loaf of banana bread
  - \$9 for a torte. 
  
Notice the use of the square brackets in the following code that appends all four values to the array at once:

In [15]:
prices = np.append(prices, [4.50, 3, 4, 9])
prices

array([ 2. ,  1. , 10. ,  7. ,  4.5,  3. ,  4. ,  9. ])

- Now let's append the new baked good's names to our names array.

In [16]:
names = np.append(names, ['fudge','cupcake','banana bread','torte'])
names

array(['brownie', 'cookie', 'cake', 'pie', 'fudge', 'cupcake',
       'banana bread', 'torte'], dtype='<U12')

### Deleting



It turns out nobody plans to make a torte, so they want to remove the price of that item from the prices array and its name from the names array.


We will use the np.delete() command, but we need to indicate which element to delete.  

We use indexing (much the same as indexing for lists) to indicate we want to remove the element at index 7 (remember to use zero-indexing) or since it is the last element, we could go from the right and use element -1.  


In [17]:
names = np.delete(names, -1)
display(names)

prices = np.delete(prices, -1)
prices

array(['brownie', 'cookie', 'cake', 'pie', 'fudge', 'cupcake',
       'banana bread'], dtype='<U12')

array([ 2. ,  1. , 10. ,  7. ,  4.5,  3. ,  4. ])


### Replacing


The club decided to raise the price of cakes from $10 to $12. We need to reflect this in our prices array.


Once again, we will need to identify the element using the index.  Cakes are at index 2.


In [18]:
print(names[2])
prices[2]

cake


10.0

In [19]:
## updating prices for cakes at index 2
prices[2] = 12

print(names[2])
prices[2]

cake


12.0

# ✍️ **Assignment Starts Here**


- You can add as many code cells as you need (or delete any that you don't need).

- **Make sure you've run all of the code before this cell.**
  - To do so, click on this text cell and then on the toolbar menu:
    - click on the `Runtime` menu
    - select `Run before`.

1) Use the enumerate function to print out the index # and name of every baked good in your `names` array.

In [20]:
# use enumerate to print the index # and name together
for i, name in enumerate(names):
  print(i,name)

0 brownie
1 cookie
2 cake
3 pie
4 fudge
5 cupcake
6 banana bread


2) Update the quantities_sold_array to include the sale of 2 pies, 3 trays of fudge, 16 cupcakes, and 5 loaves of banana bread. You also realize that one of the cookies you thought was sold had actually fallen on the ground, so edit the quantities_sold_array from 40 to 39.


In [21]:
quantities_sold = np.append(quantities_sold, [2,3,16,5])
quantities_sold[1]=39 



In [22]:
print(names)
print(quantities_sold)

['brownie' 'cookie' 'cake' 'pie' 'fudge' 'cupcake' 'banana bread']
[17 39  1  2  3 16  5]



3) Determine the amount of money collected from the sale of each item at the bake sale.

In [23]:
total_sales=sum(quantities_sold * prices)


In [24]:
total_sales

180.5

4) Create a NumPy array "quantity_leftover" that includes the quantity of each item remaining at the end of the sale: 2 cakes, 1 pie, 6 trays of fudge, 2 loaves of banana bread. Hint: Make sure to include "0" for any item that was sold out. Why is this important when creating the array?

In [25]:
rem_items_list = [0,0,2,1,6,0,2]
rem_items = np.array(rem_items_list)
rem_items



array([0, 0, 2, 1, 6, 0, 2])

In [26]:
#it's important to match the length of the arrays

5) The club decides to sell the leftover items at half price and everything quickly sells out! Determine how much money was collected from the clearance sale.

In [27]:
total_sales2 = sum(rem_items * (prices*0.5))


In [28]:
total_sales2

33.0

6) How much total money was collected from the bake sale (including the sale of full price and clearance items)?
Hint: Your final answer should be $213.50, but you must make sure you get this answer with your NumPy coding skills!!

In [29]:
total_daily_sales = total_sales + total_sales2


In [30]:
total_daily_sales

213.5

Turn in this .ipynb file with your code and your solutions.
